version: "0.1"
environments:
  - name: main
    branch: main
    mode: read
  - name: anotherBranch
    branch: anotherBranch
    mode: read
apps:
  - name: Test
    path: ""
    text-resources:
      - path: src/*.json
        format: flat-key-value
